# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uE2-3RfDAyfxMUFnr1opxS8umEjJxkom
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

for root, dirs, files in os.walk("/content/drive"):
    for d in dirs:
        if "Hasdeo" in d:
            print(os.path.join(root,d))

import os

matches = []

for root, dirs, files in os.walk("/content/drive"):
    for d in dirs:
        if d == "Hasdeo_Training_Dataset":
            matches.append(os.path.join(root,d))

matches

!pip install gdown

import gdown

gdown.download_folder(
    "https://drive.google.com/drive/folders/14tQ7B7Y_LpPTll5CUU6w3mDwlhNREm1-?usp=share_link",
    output="data",
    quiet=False
)

from google.colab import drive
drive.mount('/content/drive')

import os

for root, dirs, files in os.walk("/content/drive"):
    for d in dirs:
        if "Hasdeo_Training_Dataset" in d:
            print(os.path.join(root,d))

input_folder = "/content/drive/MyDrive/Hasdeo_Training_Dataset"

import os
os.listdir(input_folder)[:5]

import rasterio
import numpy as np
from PIL import Image
import os

output_folder = "/content/jpg_output"
os.makedirs(output_folder, exist_ok=True)

def stretch(x):
    x = np.nan_to_num(x)
    x_valid = x[x>0]
    if len(x_valid)==0:
        return np.zeros_like(x)

    p2,p98 = np.percentile(x_valid,(2,98))
    if p98-p2 == 0:
        return np.zeros_like(x)

    return np.clip((x-p2)/(p98-p2),0,1)

files = sorted([f for f in os.listdir(input_folder) if f.endswith(".tif")])[:10]

for file in files:

    path = os.path.join(input_folder,file)

    with rasterio.open(path) as src:
        r = src.read(3).astype(float)
        g = src.read(2).astype(float)
        b = src.read(1).astype(float)

    r,g,b = stretch(r), stretch(g), stretch(b)

    rgb = np.dstack((r,g,b))
    rgb = (rgb*255).astype(np.uint8)

    Image.fromarray(rgb).save(f"{output_folder}/{file}.jpg")

    print("Converted:", file)

import os
import rasterio
import numpy as np
from PIL import Image

# ==============================
# SETTINGS
# ==============================

input_folder = "/content/drive/MyDrive/Hasdeo_Training_Dataset"  # change if needed
output_folder = "/content/jpg_output"
max_images = 10
scale = 4   # 2=high quality, 4=balanced, 8=fastest

os.makedirs(output_folder, exist_ok=True)

# ==============================
# SAFE STRETCH FUNCTION
# ==============================

def stretch(x):
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)

    valid = x[x > 0]
    if len(valid) == 0:
        return np.zeros_like(x)

    p2, p98 = np.percentile(valid, (2, 98))

    if p98 - p2 == 0:
        return np.zeros_like(x)

    return np.clip((x - p2) / (p98 - p2), 0, 1)

# ==============================
# FILE LIST
# ==============================

files = sorted([f for f in os.listdir(input_folder) if f.endswith(".tif")])[:max_images]

print("Processing", len(files), "files\n")

# ==============================
# PROCESS LOOP
# ==============================

failed = []

for file in files:

    path = os.path.join(input_folder, file)

    try:
        with rasterio.open(path) as src:

            r = src.read(3, out_shape=(src.height//scale, src.width//scale))
            g = src.read(2, out_shape=(src.height//scale, src.width//scale))
            b = src.read(1, out_shape=(src.height//scale, src.width//scale))

        r = stretch(r)
        g = stretch(g)
        b = stretch(b)

        rgb = np.dstack((r, g, b))
        rgb = (rgb * 255).astype(np.uint8)

        save_path = os.path.join(output_folder, file.replace(".tif",".jpg"))
        Image.fromarray(rgb).save(save_path)

        print("✔ Converted:", file)

    except Exception as e:
        print("✖ Skipped:", file)
        failed.append((file,str(e)))

# ==============================
# REPORT
# ==============================

print("\nDone\n")

if failed:
    print("Failed Files:")
    for f,e in failed:
        print("-",f)
else:
    print("No failures")

# ==============================
# ZIP OUTPUT
# ==============================

import shutil
shutil.make_archive("converted_images","zip",output_folder)

print("\nZIP ready: converted_images.zip")

import os
import rasterio
import numpy as np
from PIL import Image
import shutil

# ==============================
# SETTINGS
# ==============================

input_folder = "/content/drive/MyDrive/Hasdeo_Training_Dataset"
output_folder = "/content/jpg_output"
scale = 4   # 2=high quality | 4=balanced | 8=fastest

os.makedirs(output_folder, exist_ok=True)

# ==============================
# STRETCH FUNCTION
# ==============================

def stretch(x):
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    valid = x[x > 0]
    if len(valid) == 0:
        return np.zeros_like(x)

    p2, p98 = np.percentile(valid, (2, 98))
    if p98 - p2 == 0:
        return np.zeros_like(x)

    return np.clip((x - p2) / (p98 - p2), 0, 1)

# ==============================
# GET ALL TIFF FILES
# ==============================

files = sorted([f for f in os.listdir(input_folder) if f.endswith(".tif")])

print("Total TIFF files:", len(files), "\n")

# ==============================
# PROCESS LOOP
# ==============================

failed = []

for i, file in enumerate(files, 1):

    path = os.path.join(input_folder, file)

    try:
        with rasterio.open(path) as src:

            r = src.read(3, out_shape=(src.height//scale, src.width//scale))
            g = src.read(2, out_shape=(src.height//scale, src.width//scale))
            b = src.read(1, out_shape=(src.height//scale, src.width//scale))

        r,g,b = stretch(r), stretch(g), stretch(b)

        rgb = np.dstack((r,g,b))
        rgb = (rgb*255).astype(np.uint8)

        save_path = os.path.join(output_folder, file.replace(".tif",".jpg"))
        Image.fromarray(rgb).save(save_path)

        print(f"[{i}/{len(files)}] ✔ {file}")

    except Exception as e:
        print(f"[{i}/{len(files)}] ✖ Skipped:", file)
        failed.append(file)

# ==============================
# ZIP OUTPUT
# ==============================

zip_path = "converted_images"
shutil.make_archive(zip_path, 'zip', output_folder)

print("\nZIP READY → converted_images.zip")

# ==============================
# FAILURE REPORT
# ==============================

if failed:
    print("\nFailed files:")
    for f in failed:
        print("-",f)
else:
    print("\nAll files processed successfully")

from google.colab import files
files.download("converted_images.zip")

